# Generated by Django 4.0.4 on 2022-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('title_1', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=200)),
                ('brief_1', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('img_main', models.ImageField(upload_to='')),
                ('img_1', models.ImageField(upload_to='')),
                ('img_2', models.ImageField(upload_to='')),
                ('img_3', models.ImageField(upload_to='')),
            ],
        ),
    ]
